### ISSUE TITLE
File I/O

### ISSUE THREAD

**Issue by takemaru** [kunisura/TdZdd#2]
Does TdZdd provide file I/O methods or SapporoBDD converters?

**Comment by kunisura** [comment]
Yes, it is.  Although TdZdd includes no file I/O methods, you can import from and export to SapporoBDD C++ objects using "tdzdd/spec/SapporoZdd.hpp" and "tdzdd/eval/ToZBDD.hpp", respectively.  They will also be good references for writing your own I/O methods.
