### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by dirocCen** [kunisura/TdZdd#6]
when I "cd ../TdZdd/apps" and "make" ,it return "ZBDD.h: no such files or directory".
![fig1](https://user-images.githubusercontent.com/58358119/133707581-036575f3-85ba-44df-b3b0-fc0797ac5d2c.png)

**Comment by kunisura** [comment]
To simply use TdZdd as a library, you do not need any application in the "apps" directory.
Some applications depend on external libraries. If you are interested in compiling apps/graphillion, you will need [SAPPOROBDD](http://www.lab2.kuis.kyoto-u.ac.jp/minato/SAPPOROBDD/). Similarly, you need [CUDD](https://github.com/ivmai/cudd) to compile apps/cnfbdd and apps/cnf2ztdd2bdd. Please get and install each library and try again, if necessary.
In any case, thank you for your comment. I will add this to the README.

**Comment by dirocCen** [comment]
Many thanks, I think it will be very usefull for us.
