### ISSUE TITLE
`tdzdd::DdStructure` の等価判定で枝が全て 0 終端節点を指すような節点が存在すると assert に落ちてしまう

### ISSUE THREAD

**Issue by suisen-cp** [kunisura/TdZdd#7]
## 環境

- OS: Windows 11 + WSL2 (Ubuntu 22.04.1 LTS)
- コンパイラ: g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

## 現象

次のコードが内部の assert に違反して等価判定に失敗します。

```cpp
#include "tdzdd/DdSpec.hpp"
#include "tdzdd/DdStructure.hpp"

constexpr int ARITY = 2; // or 3, 4, ...

struct Spec : tdzdd::StatelessDdSpec<Spec, ARITY> {
    int getRoot() const {
        return 1;
    }
    int getChild(int, int) const {
        return 0;
    }
};

int main() {
    [[maybe_unused]] tdzdd::DdStructure<ARITY>{Spec{}} == tdzdd::DdStructure<ARITY>{Spec{}};
    return 0;
}
```

実行した際のエラーメッセージは以下の通りです (ファイルパスを一部加工しました)。

```
main: /path/to/TdZdd/include/tdzdd/dd/../util/MyHashTable.hpp:337: tdzdd::MyHashTable<T, Hash, Equal>::Entry& tdzdd::MyHashTable<T, Hash, Equal>::add(const Entry&) [with T = tdzdd::MyHashMapEntry<tdzdd::InitializedNode<2>, long unsigned int>; Hash = tdzdd::MyHashMapHashWrapper<tdzdd::InitializedNode<2>, long unsigned int, tdzdd::MyHashDefault<tdzdd::InitializedNode<2> >, tdzdd::MyHashDefault<tdzdd::InitializedNode<2> > >; Equal = tdzdd::MyHashMapHashWrapper<tdzdd::InitializedNode<2>, long unsigned int, tdzdd::MyHashDefault<tdzdd::InitializedNode<2> >, tdzdd::MyHashDefault<tdzdd::InitializedNode<2> > >; tdzdd::MyHashTable<T, Hash, Equal>::Entry = tdzdd::MyHashMapEntry<tdzdd::InitializedNode<2>, long unsigned int>]: Assertion `!(elem == Entry())' failed.
Aborted
```

つまり、以下の assert に違反してしまっています。

https://github.com/kunisura/TdZdd/blob/master/include/tdzdd/util/MyHashTable.hpp#L337

## 推測される原因

- 等価判定の内部では `MyHashMap<InitializedNode<ARITY>, size_t>` が用いられ、これにノードを格納する操作が含まれている
- 問題の assert は `MyHashMap` に対する「追加するキーがデフォルトコンストラクタで構築されるオブジェクトと等価であってはならない」という制約のチェック
- キーである `InitializedNode<ARITY> : Node<ARITY>` のデフォルトコンストラクタ: https://github.com/kunisura/TdZdd/blob/cb07fc92b5554d581db1e07cfa802787e622579b/include/tdzdd/dd/Node.hpp#L197-L199
    - 子の `tdzdd::NodeId` が全て 0 であるようなノードを構築している
- `tdzdd::NodeId` が 0 であるというのは即ち 0 終端節点
- つまり、子節点が全て 0 終端節点であるようなノードが存在するような `tdzdd::DdStructure` を等価判定に与えた場合に assert に違反してしまう

**Comment by kunisura** [comment]
報告ありがとうございます。
ですが、すぐには時間が取れそうにありませんので、対応まで少しお待ちください。
その間に新情報や解決案などがありましたら、コメント追加頂けると助かります！

**Comment by kunisura** [comment]
`InitializedNode<ARITY> : Node<ARITY>` のデフォルトコンストラクタを変更することで問題を回避しました。
